### ISSUE TITLE
Fix plugin authorship metadata

### ISSUE THREAD

**Issue by benlk** [INN/term-debt-consolidator#17]
https://wordpress.org/plugins/term-debt-consolidator/ doesn't list https://profiles.wordpress.org/inn_nerds/ as its author, and as a result it doesn't show up in https://profiles.wordpress.org/inn_nerds/#content-plugins

**Comment by rclachance** [comment]
that's weird - this should be fixed in the new version, and be switched over to use our new account - https://profiles.wordpress.org/innlabs#content-plugins

**Comment by benlk** [comment]
Maybe it's a mismatch between the plugin readme.txt and the plugin's main php file?

**Comment by benlk** [comment]
Yeah, it's fixed in the new version. Won't be a problem once the new version is deployed.
